name: Godot CI/CD

on:
  push:
    branches:
      - ci-cd
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install Godot
        run: |
          curl -L -o godot.exe.zip "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_win64.exe.zip"
          & "C:\Program Files\7-Zip\7z.exe" x godot.exe.zip -aoa
          Rename-Item -Path "Godot_v4.3-stable_win64.exe" -NewName "godot.exe"

      - name: Download Godot Export Templates
        run: |
          # Create the export_templates directory using PowerShell
          New-Item -ItemType Directory -Force "$env:APPDATA\Godot\export_templates"

          # Download the export templates file
          Invoke-WebRequest -Uri "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz" -OutFile "templates.zip"

          # Extract the templates.zip archive to the export_templates directory using 7-Zip
          & "C:\Program Files\7-Zip\7z.exe" x templates.zip -aoa -o"$env:APPDATA\Godot\export_templates"

      - name: Build Game
        run: |
          # Create a directory for the web build
          New-Item -ItemType Directory -Force "build\web"
          # Build the game using Godot with the "Web" export preset
          .\godot.exe -v --headless --export-release "Web" "build\web\index.html"

      - name: List build/windows Directory Contents
        run: |
          Write-Host "Listing contents of build/web:"
          Get-ChildItem -Recurse .\build\web\

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-build
          path: ./build/windows/game.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/windows/game.exe
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
